spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
cache:
  config:
    entryTtl: 60
    countryNames:
      entryTtl: 30